# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GbMQHufAn_8tLI7vJCUHjhAR81U4DOK
"""

### MEUS TESTES DE ESTUDO ###

# String nome e Imprimir

nome='Wesley'
print('Seja bem vindo',nome,)


# Indentação correta (01)|Indentação Incorreta (02)
# código 01
x = 4
if x > 5:
 x = x * 2
 print(x)
print('fim')

# código 02
x = 4
if x > 5:
 x = x * 2
print(x)
print('fim')

#Operações Matemáticas

w=1.0
e=2.0
s=3.0

media=(w+e+s)/3
print(media)

#Conceito PEMDAS na linguagem Python
P Parênteses
E Exponenciação
M Multiplicação
D Divisão
A Adição
S Subtração

B = 15 # Base maior (B)
b = 10 # Base menor (b)
h = 8 # Altura (h)
# Calcula a área do Trapézio

area = B + b * h / 2
print('Área do Trapézio: ', area)

Resultado: Área do Trapézio:  55.0

OBS: De acordo com PEMDAS, o cálculo foi o seguinte b*h/2+B que foi o resultado acima.
    
Portanto, para corrigirmos o código, é necessário priorizar a adição B + b, por meio da declaração de parênteses:

area = (B + b) * h / 2
print('Área do Trapézio: ', area)

Resultado: Área do Trapézio:  100.0
        
# Operadores:

> Maior Verdadeiro (True) se o operando da esquerda for
maior que o operando da direita.
x > y

>= Maior ou igual Verdadeiro (True) se o operando da esquerda for
maior ou igual que o operando da direita.
x >= y

< Menor Verdadeiro (True) se o operando da esquerda for
menor que o operando da direita.
x < y

<= Menor ou igual Verdadeiro (True) se o operando da esquerda for
menor ou igual que o operando da direita.
x <= y

== Igual Verdadeiro (True) se os dois operandos são iguais
(possuem o mesmo valor).
x == y

!= Diferente Verdadeiro (True) se os dois operandos são
diferentes (não possuem o mesmo valor).
x != y
        
Exemplos:
    
x = 5
y = 1
s = 'palavra'
print('x > y:', x > (y + 2))
print('x <= 4.564:', x <= (4.564 + 1))
print('s == palavra:', s != 'palavra')
print('(y * 0) == False:', (y * 0) == False)
print('s != abacaxi:', s != 'abacaxi')

Resultados:
x > y: True
x <= 4.564: True
s == palavra: False
(y * 0) == False: True
s != abacaxi: True    

    
#OPERAÇÃO DESCRIÇÃO UTILIZAÇÃO

and Conjunção Verdadeiro (True) se, e somente se, os dois
operandos também forem verdadeiros.
x and y

or Disjunção Verdadeiro (True) se qualquer um dos dois
operandos for verdadeiro também.
x or y

not Complemento
Inverte o valor do operando (complemento).
Verdadeiro (True) se o operando for falso. Falso
(False) se o operando for verdadeiro.
not x
   
#Teste: Verifica se uma pessoa pode dirigir

# verifica se uma pessoa pode dirigir
idade = 23
possui_cnh = False
print(idade > 18 and possui_cnh)

# verifica se um passageiro pode viajar sozinho
idade = 15
possui_autorizacao = True
print(idade > 18 or possui_autorizacao)

Resultado:
False
True


#Teste: Verifica se atingiu média necessária para passa de ano

#Felipe
matematica = 5
portugues = 4
ingles = 7
historia = 6

media = (matematica+portugues+ingles+historia)/4
falta = True

print(media>=5 == falta)
Resultado:
False


