# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GbMQHufAn_8tLI7vJCUHjhAR81U4DOK
"""

# String nome e Imprimir

nome='Wesley'
print('Seja bem vindo',nome,)


# Indentação correta (01)|Indentação Incorreta (02)
# código 01
x = 4
if x > 5:
 x = x * 2
 print(x)
print('fim')

# código 02
x = 4
if x > 5:
 x = x * 2
print(x)
print('fim')

